export interface languageState{
    language:string,
    login:{
        main:string,
        haveAccount:string,
        toRegistration:string,
        email:string,
        password:string,
        toCafeAccount:string,
        toUserAccount:string,
        btn:string
    },
    header:{
        login:string,
        registration:string
    },
    registration:{
        main:string,
        haveAccount:string,
        toLogin:string,
        toUser:string,
        toCaffe:string,
        name:string,
        cafeName:string,
        email:string,
        password:string,
        confirmPassword:string,
        agree:string,
        terms:string,
        and:string,
        policy:string,
        register:string
    }

}
export interface langItem{
    name:string,
    img:number,
    type:string
}