export interface languageState{
    language:string,
    login:{
        main:string,
        haveAccount:string,
        toRegistration:string,
        email:string,
        password:string,
        toCafeAccount:string,
        toUserAccount:string,
        btn:string
    },
    header:{
        login:string,
        registration:string,
        order:string,
        activeOrders:string,
        profile:string,
        history:string,
        logout:string,
        orders:string
    },
    registration:{
        main:string,
        haveAccount:string,
        toLogin:string,
        toUser:string,
        toCaffe:string,
        name:string,
        cafeName:string,
        email:string,
        password:string,
        confirmPassword:string,
        agree:string,
        terms:string,
        and:string,
        policy:string,
        register:string
    },
    userProfile:{
        title:string,
        name:string,
        phone:string,
        bank:string,
        cardNumber:string,
        update:string,
        makeOrder:string,
        chooseBank:string,
        updateTitle:string,
        chooseAvatar:string,
        makeDefault:string,
        save:string

    },
    cafeProfile:{
        title:string,
        name:string,
        city:string,
        address:string,
        phone:string,
        positions:string,
        item:string,
        price:string,
        update:string
    },
    pageTitles:{
        acitveOrders:string,
        cafeProfile:string,
        history:string,
        mainPage:string,
        login:string,
        orderPage:string,
        ordersPage:string,
        privacyPolicy:string,
        userProfile:string,
        registration:string,
        terms:string
    },
    alerts:{
        successReg:string,
        orderInWork:string,
        orderIsFinished:string,
        orderIsDone:string,
        successOrder:string,
        profileUpdated:string
    },
    history:{
        title:string,
        noItems:string,
        coffeeName:string,
        userName:string,
        positions:string,
        date:string
    },
    order:{
        title:string,
        chooseSity:string,
        chooseAddress:string,
        noShops:string,
        makeOrder:string,
        positions:string,
        modalTitle:string,
        modalSubtitle:string,
        chooseDrink:string,
        add:string,
        orderList:string,
        confirmOrder:string,
        closeModal:string,
        emptyList:string,
        totalPrice:string
    },
    mainPage:{
        title:string,
        card1:string,
        card2:string,
        card3:string,
        card3First:string,
        card3Second:string,
        card3Third:string,
        card3Four:string,
        card4:string
    }

}
export interface langItem{
    name:string,
    img:number,
    type:string
}