export interface languageState{
    language:string,
    login:{
        main:string,
        haveAccount:string,
        toRegistration:string,
        email:string,
        password:string,
        toCafeAccount:string,
        toUserAccount:string,
        btn:string
    },
    header:{
        login:string,
        registration:string,
        order:string,
        activeOrders:string,
        profile:string,
        history:string,
        logout:string,
        orders:string
    },
    registration:{
        main:string,
        haveAccount:string,
        toLogin:string,
        toUser:string,
        toCaffe:string,
        name:string,
        cafeName:string,
        email:string,
        password:string,
        confirmPassword:string,
        agree:string,
        terms:string,
        and:string,
        policy:string,
        register:string
    },
    userProfile:{
        title:string,
        name:string,
        phone:string,
        bank:string,
        cardNumber:string,
        update:string,
        makeOrder:string,
        chooseBank:string,
        updateTitle:string,
        chooseAvatar:string,
        makeDefault:string,
        save:string

    },
    cafeProfile:{
        title:string,
        name:string,
        city:string,
        address:string,
        phone:string,
        positions:string,
        item:string,
        price:string,
        update:string
    }

}
export interface langItem{
    name:string,
    img:number,
    type:string
}